#docker run -d --name=Filebrowser --restart=always -p 8082:80 -v /:/srv filebrowser/filebrowser:latest

version: "3.3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - /:/srv
    ports:
      - "8082:80"
