version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pgweb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pgweb
    ports:
      - 5432:5432
  pgweb:
    image: sosedoff/pgweb:latest
    environment:
      - PGWEB_DATABASE_URL=postgresql://pgweb:password@postgres:5432/pgweb?sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      - postgres
