version: '3'

services:
   portainer:
      image: portainer/portainer:latest
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      ports:
         - '9000:9000'
   filebrowser:
      image: filebrowser/filebrowser
      volumes:
         - /:/srv
      ports:
         - '81:80'
   postgres:
      image: postgres:13.9
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=test
      ports:
         - 5432:5432
   pgadmin:
      image: dpage/pgadmin4
      environment:
         - 'PGADMIN_DEFAULT_EMAIL=user@domain.com'
         - 'PGADMIN_DEFAULT_PASSWORD=SuperSecret'
      ports:
         - 82:80
      depends_on:
         - postgres
